services:
  user-management:
    container_name: user-management
    image:
      user-management-image
    build:
      context: services/user-management/
      dockerfile: Dockerfile
    environment:
      CLIENT_ID : "${CLIENT_ID}"
      CLIENT_SECRET : "${CLIENT_SECRET}"
      REDIRECT_URI : "${REDIRECT_URI}"
    # ports:
    #   - "443:443"
    # volumes:
    #   - wordpress:/var/www/wordpress
    networks:
      - transcendence
    # depends_on:
    #   - wordpress
    restart: always
  
  website:
    container_name: website
    image:
      website-image
    build:
      context: services/website/
      dockerfile: Dockerfile
    depends_on:
      - user-management
    networks:
      - transcendence
    environment:
      - name=value
    ports:
      - "8000:8000"
    restart: always
  
  # cadvisor:
  #   container_name: cadvisor
  #   build:
  #     context: bonus/cadvisor/
  #     dockerfile: Dockerfile
  #   image: cadvisor
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - inception
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always

# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o:  'bind'
#       device: /home/ychalant/data/wordpress
#   db:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o:  'bind'
#       device: /home/ychalant/data/mariadb

networks:
  transcendence:
    driver: bridge