services:
  user-management:
    container_name: user-management
    image:
      user-management-image
    build:
      context: services/user-management/
    # environment:

    # ports:
    #   - "443:443"
    # volumes:
    #   - wordpress:/var/www/wordpress
    networks:
      - transcendence
    depends_on:
      - postgresql
    restart: always
  
  website:
    container_name: website
    image:
      website-image
    build:
      context: services/website/
    depends_on:
      - user-management
    networks:
      - transcendence
    environment:
      CLIENT_ID : "${CLIENT_ID}"
      CLIENT_SECRET : "${CLIENT_SECRET}"
      REDIRECT_URI : "${REDIRECT_URI}"
      POSTGRES_USER : "${POSTGRES_USER}"
      POSTGRES_PASSWORD : "${POSTGRES_PASSWORD}"
    ports:
      - "8000:8000"
    restart: always
  
  postgresql:
    container_name: postgresql
    image:
      postgresql-image
    build:
      context: services/postgreSQL
    networks:
      - transcendence
    environment:
      POSTGRES_USER : "${POSTGRES_USER}"
      POSTGRES_PASSWORD : "${POSTGRES_PASSWORD}"
    restart: always
    

  

# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o:  'bind'
#       device: /home/ychalant/data/wordpress
#   db:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o:  'bind'
#       device: /home/ychalant/data/mariadb

networks:
  transcendence:
    driver: bridge