name: Test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install tools
      run: sudo apt install make docker
    - name: Build project
      run: docker compose -f src/docker-compose.yaml build
  
