name: Test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Install tools
      run: sudo apt-get update && sudo apt-get install docker
    - name: Build project
      run: docker compose -f src/docker-compose.yaml build
  
